using System;
using System.Linq;

namespace ProjectEuler
{
    public class EvenFibonacciNumbers : IProblem
    {
        public int Id => 2;

        public string Title => "Even Fibonacci numbers";

        public string Description => "Each new term in the Fibonacci sequence is generated by adding the previous two terms." +
            " By starting with 1 and 2, the first 10 terms will be:" +
            "\n" +
            "\t1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ..." +
            "\n" +
            "By considering the terms in the Fibonacci sequence whose values do not exceed four million, " +
            "find the sum of the even-valued terms.";

        public string Solution => $"sum equals {GetSum(4000000)}";

        private int GetSum(int limit)
        {
            int sum = 0;
            int num1 = 1;
            int num2 = 2;

            while (num1 < limit)
            {
                if (num1 % 2 == 0)
                {
                    sum += num1;
                }
                var temp = num1 + num2;
                num1 = num2;
                num2 = temp;
            }

            return sum;
        }
    }
}
